training: 

  gamma: 0.99

  lr: 0.01

  train_batch_size: 50000

  model:
    fcnet_hiddens: [256, 256]
    fcnet_activation: swish
    vf_share_layers: false
    free_log_std: true

  optimizer: 
    type: adam
    eps: 1e-08

  use_critic: true

  use_gae: true

  lambda_: 0.95

  kl_coeff: 0.2

  sgd_minibatch_size: 9000

  num_sgd_iter: 6


  vf_loss_coeff: 0.5

  entropy_coeff: 0.01

  clip_param: 0.2

  vf_clip_param: 10

  kl_target: 0.01

environment:

  env: cassie-v0

  clip_actions: true

  disable_env_checking: true

framework:

  framework: tf2

  eager_tracing: true

rollouts: 
  recreate_failed_workers: true  
  
  num_workers: 20

  rollout_fragment_length: auto

  batch_mode: truncate_episodes

  observation_filter: NoFilter  

evaluation: 

  evaluation_interval: 2

  evaluation_duration: 20

resources: 

  num_gpus: 1
  num_cpus_per_worker: 1
  num_gpus_per_worker: 0.05
