
framework: torch
log_level: WARN
num_gpus: 0
num_cpus: 8
num_workers: 50
num_envs_per_worker: 1
rollout_fragment_length: 300
train_batch_size: 50000
sgd_minibatch_size: 9000
observation_space: null
num_sgd_iter: 5
optimizer:
  type: Adam
  lr: 0.0003
  epsilon: 0.00005
model:
  fcnet_activation: swish
  fcnet_hiddens: [!!int 256,!!int 256,!!int 128,!!int 64]
  vf_share_layers: false
  free_log_std: true
entropy_coeff: 0.01
gamma: 0.99
lambda: 0.95
kl_coeff: 0.5
clip_param: 0.2
batch_mode: truncate_episodes
observation_filter: NoFilter
reuse_actors: true
disable_env_checking: true
num_gpus_per_worker: 0
num_cpus_per_worker: 0.16
evaluation_interval: 2
evaluation_num_episodes: 10
evaluation_config:
  env: cassie-v0
  seed: 1234
