training: 

  gamma: 0.99

  lr: 0.01

  train_batch_size: 1000

  model:
    fcnet_hiddens: [64, 64]
    fcnet_activation: swish
    vf_share_layers: false
    free_log_std: true

  optimizer: 
    type: adam
    eps: 1e-06

  use_critic: true

  use_gae: true

  lambda_: 0.95

  kl_coeff: 0.2

  sgd_minibatch_size: 200

  num_sgd_iter: 10

  vf_loss_coeff: 0.5

  entropy_coeff: 0.01

  clip_param: 0.2

  kl_target: 0.01

environment:

  env: cassie-v0

  disable_env_checking: true

framework:
  framework: torch


rollouts: 
  recreate_failed_workers: true  

  num_workers: 10

  num_envs_per_worker: 2

  rollout_fragment_length: auto

  batch_mode: truncate_episodes

  observation_filter: NoFilter
  
  reuse_actors: true

evaluation: 

  evaluation_interval: 2

  evaluation_duration: 10
