#PPO config for snake

# Environment
env: snake-v0
num_workers: 1
num_gpus: 1
num_cpus_per_worker: 1

framework: torch
optimizer:
    # Adam optimizer
    type: Adam
    # Learning rate
    lr: 0.0001
    # Adam epsilon hyper parameter
    eps: 0.01
#ppo config 
kl_coeff: 0.2
num_sgd_iter: 10
clip_param: 0.2
sgd_minibatch_size: 128
train_batch_size: 4096
gamma: 0.99
lambda: 0.95
vf_loss_coeff: 0.5
entropy_coeff: 0.01
use_gae: True
kl_target: 0.01
use_critic: True

#the model has two dense layers with 64 neurons each
model:
    fcnet_hiddens: [64,64]
    fcnet_activation: swish