#PPO config for snake

# Environment
env: snake-v0
num_workers: 4
num_gpus_per_worker: 0.25
num_cpus_per_worker: 5
disable_env_checking: True
framework: tf2
use_eager_tracing: True

optimizer:
    # Adam optimizer
    type: Adam
    # Learning rate
    lr: 0.001
    # Adam epsilon hyper parameter
    eps: 0.01

# Exploration
exploration_config:
  type: "EpsilonGreedy"
  initial_epsilon: 0.5
  final_epsilon: 0.01
  epsilon_timesteps: 100000

#ppo config 
kl_coeff: 0.2
batch_mode: truncate_episodes

num_sgd_iter: 5
clip_param: 0.2
sgd_minibatch_size: 2000
train_batch_size: 10000
gamma: 0.9
lambda: 0.95
vf_loss_coeff: 0.5
entropy_coeff: 0.01
use_gae: True
kl_target: 0.01
use_critic: True
recreate_failed_workers: True
reuse_actors: True

#the model has two dense layers with 64 neurons each
model:
    fcnet_hiddens: [64,64]
    fcnet_activation: swish
    vf_share_layers: false 
    free_log_std: true
